grafana_version: "12.2.0"
grafana_dist: "linux-amd64"
grafana_install_dir: /opt
grafana_prefix_dir: "{{ grafana_install_dir }}/grafana-{{ grafana_version }}"

# Synlink to the selected version of Grafana
grafana_current_link: "{{ grafana_install_dir }}/grafana"

grafana_archive: "/tmp/grafana-{{ grafana_version }}.{{ grafana_dist }}.tar.gz"
grafana_download_url: "https://dl.grafana.com/grafana/release/12.2.0/grafana_12.2.0_17949786146_linux_amd64.tar.gz"
grafana_checksum: "sha256:c4f53551ed4887c792caeb9d02fa0c1a36e3db9ee8bdda32b1ced810cb135a93"  # optionally: sha256:...

# Runtime
grafana_ini_path: /etc/grafana/grafana.ini
grafana_etc_dir: /etc/grafana
grafana_provisioning_dir: "{{ grafana_etc_dir }}/provisioning"
grafana_data_dir: /var/lib/grafana

grafana_user: grafana
grafana_group: grafana
grafana_http_port: 3000

grafana_admin_user: namdp_zops
grafana_admin_password: namdp_zops

