- name: Create victoria user (shared with victoria-metrics)
  ansible.builtin.user:
    name: "{{ victoria_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Download vmutils archive (pinned)
  ansible.builtin.get_url:
    url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoria_version }}/vmutils-{{ victoria_kernel }}-{{ victoria_arch }}-{{ victoria_version }}.tar.gz"
    dest: /tmp/vmutils.tar.gz
    mode: "0644"
    checksum: "{{ vmutils_archive_checksum }}"
  register: vmutils_tar

- name: Ensure temp dir exists
  ansible.builtin.file:
    path: /tmp/vmutils_extract
    state: directory
    owner: "{{ victoria_user }}"
    group: "{{ victoria_group | default(victoria_user) }}"
    mode: "0755"

- name: Unpack archive to temp dir
  ansible.builtin.unarchive:
    src: /tmp/vmutils.tar.gz
    dest: /tmp/vmutils_extract
    remote_src: true

- name: Install selected vmutils binaries
  ansible.builtin.copy:
    src: "/tmp/vmutils_extract/{{ item }}"
    dest: "{{ vmutils_bin_dir}}/{{ item }}"
    remote_src: true
    owner: "{{ victoria_user }}"
    group: "{{ victoria_group | default(victoria_user) }}"
    mode: "0755"
  loop:
    - vmagent-prod

- name: Clean up temp dir
  ansible.builtin.file:
    path: /tmp/vmutils_extract
    state: absent

- name: Ensure vmagent config dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ victoria_user }}"
    group: "{{ victoria_group }}"
    mode: "0755"
  loop:
    - "{{ vmagent_config_dir }}"
    - "{{ vmagent_tmp_path }}"

- name: Render vmagent scrape.yml
  ansible.builtin.template:
    src: vmagent-scrape.yml.j2
    dest: "{{ vmagent_scrape_config_path }}"
    owner: "{{ victoria_user }}"
    group: "{{ victoria_group }}"
    mode: "0644"
  notify: supervisor changed
  when: vmagent_enabled

- name: Drop supervisord program for vmagent
  ansible.builtin.template:
    src: vmagent.supervisor.conf.j2
    dest: "{{ supervisord_conf_dir }}/vmagent.conf"
    owner: root
    group: root
    mode: "0644"
  notify: supervisor changed
  when: vmagent_enabled
