- name: Ensure dirs exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/nftables.d/global
    - /etc/nftables.d/groups
    - /etc/nftables.d/hosts
    - /etc/nftables.d/custom

- name: Remove all contents inside nftables.d dirs
  become: true
  shell: "rm -rf {{ item }}/*"
  loop:
    - /etc/nftables.d/global
    - /etc/nftables.d/groups
    - /etc/nftables.d/hosts
    - /etc/nftables.d/custom

- name: Render /etc/nftables.conf
  become: true
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0644"
  notify: reload nftables
