- name: Ensure nftables present
  package:
    name: nftables
    state: present

- name: Disable legacy iptables-services if installed
  service:
    name: iptables
    state: stopped
    enabled: false
  ignore_errors: true

- name: Ensure nftables service enabled
  service:
    name: nftables
    state: started
    enabled: true

- name: Render nftables config
  template:
    src: nftables.conf.j2
    dest: "{{ fw_nft_conf_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
    validate: "nft -c -f %s"
  register: nft_conf

- name: Reload nftables service
  systemd:
    name: nftables
    state: reloaded
  when: nft_conf.changed

