- name: Setup app deployment environment
  hosts: app
  become: true

  vars:
    firewall_nft_snippet_src_root: "{{ playbook_dir }}/../firewall"
    firewall_nft_enable_baseline: false
    firewall_nft_include_globs:
      - "{{ firewall_nft_snippet_dst_root }}/global/*.nft"
      - "{{ firewall_nft_snippet_dst_root }}/groups/app.nft"

  tasks:
    - name: Common setup
      ansible.builtin.import_role:
        name: common

    - name: SSH configuration
      ansible.builtin.import_role:
        name: sshd

    - name: UNIX identity
      ansible.builtin.import_role:
        name: unix_identity

    - name: Firewall configuration
      ansible.builtin.import_role:
        name: firewall
