- name: Setup app deployment environment
  hosts: app
  become: true

  vars:
    fw_allow_icmp: true
    fw_persist: true
    fw_inbound_rules:
    - { proto: tcp, port: 8000, action: accept, comment: "HTTP" }

  tasks:
    - name: Common setup
      ansible.builtin.import_role:
        name: common

    - name: SSH configuration
      ansible.builtin.import_role:
        name: sshd

    - name: UNIX identity
      ansible.builtin.import_role:
        name: unix_identity

    - name: Firewall configuration
      ansible.builtin.import_role:
        name: firewall
