- name: Setup app deployment environment
  hosts: app
  become: true
  tasks:
    - name: Common setup
      ansible.builtin.import_role:
        name: common

    - import_tasks: tasks/install_docker.yml
