- name: Setup app deployment environment
  hosts: app
  become: true
  tasks:
    - name: Setup hostname
      ansible.builtin.hostname:
        name: "app-{{ inventory_hostname }}"

    - import_tasks: tasks/install_docker.yml

    - name: Install packages for deployment
      ansible.builtin.apt:
        name:
          - git
        state: present
        update_cache: yes
