- name: Common setup for all of hosts
  hosts: prod
  become: true

  vars:
    common_packages:
      - curl
      - vim
      - wget
      - dnsutils


  tasks:
    - name: Common setup
      ansible.builtin.import_role:
        name: common
