- name: Common setup for all of hosts
  hosts: all
  become: true

  vars:
    common_packages:
      - curl
      - vim
      - wget
      - dnsutils

  tasks:
    - name: Common setup
      ansible.builtin.import_role:
        name: common

    - name: SSH configuration
      ansible.builtin.import_role:
        name: sshd

    - name: UNIX identity
      ansible.builtin.import_role:
        name: unix_identity
