- name: Setup ZA virtual macine
  hosts: za_vm
  become: true
  tasks:
    - name: Common setup
      ansible.builtin.import_role:
        name: common

    - name: SSH configuration
      ansible.builtin.import_role:
        name: sshd

    - name: UNIX identity
      ansible.builtin.import_role:
        name: unix_identity


