- name: Provision gitlab
  hosts: gitlab
  become: true
  roles:
    - docker
    - gitlab
  vars:
    pkg_proxy_runtime_enable: true
    pkg_http_proxy:  "http://10.40.30.21:81"
    pkg_https_proxy: "http://10.40.30.21:81"
    pkg_no_proxy:    "127.0.0.1,localhost,10.0.0.0/8"

    docker_daemon_proxy_enable: true
    docker_http_proxy:  "http://10.40.30.21:81"
    docker_https_proxy: "http://10.40.30.21:81"

    gitlab_image_pull: true
    gitlab_ports:
      http: 8080
      ssh: 2222

    gitlab_external_url: "http://{{ ansible_default_ipv4.address }}:{{ gitlab_ports.http }}"
