---
- name: "Check existing runners"
  command: >
    docker compose -p {{ gitlab_runner_project_name }}
    -f {{ gitlab_runner_compose_dir }}/docker-compose.yml
    exec -T gitlab-runner gitlab-runner list
  register: runner_list
  changed_when: false
  failed_when: false

- name: "Register runner"
  when: runner_list.rc != 0 or ('No runners found' in (runner_list.stdout | default('')))
  command: >
    docker compose -p {{ gitlab_runner_project_name }}
    -f {{ gitlab_runner_compose_dir }}/docker-compose.yml
    exec -T gitlab-runner gitlab-runner register --non-interactive
    --url "{{ gitlab_runner_url }}"
    --registration-token "{{ gitlab_runner_registration_token }}"
    --executor "docker"
    --description "{{ gitlab_runner_name }}"
    --docker-image "docker:27"
    {% if gitlab_runner_mode == 'dind' %}--docker-privileged "true"{% else %}--docker-privileged "false"{% endif %}
    --tag-list "{{ gitlab_runner_tags | join(',') }}"
    --run-untagged="{{ (gitlab_runner_run_untagged | bool) | ternary('true','false') }}"
    --locked="{{ (gitlab_runner_locked | bool) | ternary('true','false') }}"
    --access-level "{{ gitlab_runner_access_level }}"
  register: register_cmd
  changed_when: register_cmd.rc == 0

