env: "prod"

# hostname template across hosts in production
hostname: "{{ '%s-%s-%02d' | format(env, service, seq) }}"

common_packages:
  - curl
  - vim
  - wget
  - dnsutils

# Unix identity configuration (users, groups)
# common groups for production environment.
unix_groups:
  - "ops"
  - "sec"
  - "dev"
  - "deploy"
  - "dbadmin"
  - "docker"

users:
  - name: "deploy"
    groups: ["deploy", "docker"]
    system: false
    create_home: true
    # TODO: How to define expiration time?
    pubkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINX09wjV0a8FRDuOVK5tjRb0eJVRyeG1+e05SU/uJkRa lap14089@LAP14089-NamDP"

    # NOTE: name format: user's ID in the corporation/business + team name
    # for simplicity, I use a common public key for these users.

    # system team lead
  - name: "namdp-zsys"
    groups: ["ops"]
    system: false
    create_home: true
    pubkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINX09wjV0a8FRDuOVK5tjRb0eJVRyeG1+e05SU/uJkRa lap14089@LAP14089-NamDP"

    # Security team lead
  - name: "namtp-zsec"
    groups: ["sec"]
    system: false
    create_home: true
    pubkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINX09wjV0a8FRDuOVK5tjRb0eJVRyeG1+e05SU/uJkRa lap14089@LAP14089-NamDP"

    # Back-end team lead
  - name: "namtp-be"
    groups: ["dev"]
    system: false
    create_home: true
    pubkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINX09wjV0a8FRDuOVK5tjRb0eJVRyeG1+e05SU/uJkRa lap14089@LAP14089-NamDP"

    # Database admin
  - name: "namdp-dbadmin"
    groups: ["dbadmin"]
    system: false
    create_home: true
    pubkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINX09wjV0a8FRDuOVK5tjRb0eJVRyeG1+e05SU/uJkRa lap14089@LAP14089-NamDP"


# SSH server configuration
ssh_port: 22
permit_root_login: "prohibit-password"
allow_tcp_forwarding: "yes"

# Port of inner services
backend_http_port: 8000
victoria_http_port: 8428
grafana_http_port: 3000
node_exporter_port: 9100
percona_mysql_port: 3306

ansible_managed: "Generated by Ansible on {{ '%Y-%m-%d %H:%M:%S %Z' | strftime(ansible_date_time.epoch | int) }} (controller={{ inventory_hostname }})"
