env: "prod"

# common groups for production environment.
unix_groups:
  - "ops"
  - "sec"
  - "dev"
  - "deploy"
  - "dbadmin"
  - "docker"

# hostname template across hosts in production
hostname: "{{ '%s-%s-%02d' | format(env, service, seq) }}"
