- name: Validate ruleset (dry-run)
  ansible.builtin.command: nft -c -f /etc/nftables.conf
  listen: reload nftables

- name: Apply rules atomically
  ansible.builtin.command: nft -f /etc/nftables.conf
  listen: reload nftables
