- name: supervisorctl reread
  listen: supervisor changed
  ansible.builtin.command: supervisorctl reread

- name: supervisorctl update
  listen: supervisor changed
  ansible.builtin.command: supervisorctl update
