- name: validate mysql config (restart)
  listen: restart mysql
  ansible.builtin.command:
    argv:
      - "{{ percona_mysql_server_bin }}"
      - "--defaults-file={{ percona_mysql_main_conf }}"
      - "--validate-config"
  register: mysql_validate_restart
  changed_when: false
  failed_when: mysql_validate_restart.rc != 0

- name: restart mysql
  listen: restart mysql
  ansible.builtin.service:
    name: "{{ percona_mysql_service_name }}"
    state: restarted
