[project]
name = "mysql-backup-script"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python>=9.4.0",
    "pyyaml>=6.0.3",
    "typer>=0.19.2",
]
