---
# Install Percona Server for MySQL 8.0 on RHEL/CentOS/Rocky/Alma

- name: Install percona-release (repo config RPM)
  dnf:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present
  become: true

# Percona docs use `percona-release setup ps-80` on DNF-based systems
- name: Configure Percona PS 8.0 repo (setup)
  command: percona-release setup ps-80
  register: percona_release_setup
  changed_when: "'Enabling the Percona Server 8.0 repository' in percona_release_setup.stdout or percona_release_setup.rc == 0"
  become: true

- name: Enable ps-80 release repo
  command: percona-release enable ps-80 release
  register: percona_release_enable
  changed_when: "'Enabling the Percona Server 8.0 repository' in percona_release_enable.stdout or percona_release_enable.rc == 0"
  become: true

- name: Install Percona Server for MySQL 8.0
  dnf:
    name: percona-server-server
    state: present
  become: true
